apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: application
  labels:
    appname: application
    env: dev
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    appname: application
    env: dev
