apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: application
  labels:
    appname: application
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: application  
      env: dev                       
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        appname: application
        env: dev
      annotations:
        checksum/grafana-config: f3697c98a79fc4a11c1d616d869584f4
    spec:
      containers:
      - name: application
        image: gersontpc/desafio-sre-app:v1.0.0-x64
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_SDK_DISABLED
          value: "False"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://trace-jaeger-collector.monitoring:4318/v1/traces"
        - name: OTEL_SERVICE_NAME
          value: "application"
        - name: OTEL_INSTRUMENTATION_LIBRARY_NAMES
          value: "java.util.logging"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext: {}
      serviceAccountName: application