{
 "title": "Four Golden Signals",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "application" }
  ]
 },
 "panels": [
  {
   "title": "Traffic by URI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency URI /",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds{quantile=\"0.99\",namespace=\"application\",uri=\"/\"})",
     "legendFormat": "99th"
    },
    {
     "expr": "sum(http_server_requests_seconds{quantile=\"0.95\",namespace=\"application\",uri=\"/\"})",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(http_server_requests_seconds{quantile=\"0.5\",namespace=\"application\",uri=\"/\"})",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/\",status!~\"2.*\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\"})",
     "legendFormat": "quota - limits"
    },
    {
     "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Running pods"
    }
   ]
  }
 ]
}