{
 "title": "SPG",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic by URI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{}[1m])) by (uri,method,status)",
       "legendFormat": "{{method}} - {{uri}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "k8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Qty PODs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"application\"}) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"application\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"application\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "max(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"application\"})",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",namespace=\"application\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"application\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "max(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"application\"})",
       "legendFormat": "quota - limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log level",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total[1m])) by (level)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loki - LOGs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "{app=\"application\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jaeger - Traces",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "operation": "GET /", "service": "application" }
     ]
    }
   ]
  }
 ]
}